#!/bin/bash

# options:
# $1: the wasm generated by solang
# $2: the function name that you want to set as entry for zkwasm

# link input wasm with the prebuilt solang wasm to resolve dependency
link_wasm() {
  wasm-ld $1 dep.wasm -o tmp.wasm
}

# insert zkmain function with provided entry function
generate_zkmain() {
  :
}

input_wasm=$1
entry_function=$2

main() {
  link_wasm()
  generate_zkmain()
}
